services:
  # image project
  forum:
    build:
      args:
        user: milena
        uid: 1000
      context: .
      dockerfile: Dockerfile
    container_name: forum_app
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - forum_redis
    networks:
      - forum_network

  # nginx
  forum_nginx:
    image: nginx:alpine
    container_name: forum_nginx
    ports:
      - "8003:80"
      # - "5173:5173" # Adicionando a porta do Vite
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - forum_network

  # db mysql
  db_forum :
    image: mysql:8.0
    platform: linux/x86_64
    container_name: db_forum
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
      MYSQL_USER: ${DB_USERNAME:-username}
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    ports:
      - "3303:3306"
    networks:
      - forum_network

  # redis
  forum_redis:
    image: redis:latest
    container_name: forum_redis
    ports:
      - "6373:6379"
    networks:
      - forum_network

networks:
  forum_network:
    driver: bridge
